POST http://localhost:3000/analytics/report-visit
Content-Type: application/json

{
"continentCode": "EU",
"countryName": "France",
"cityName": "Paris"
}

# {
# "continentCode": "EU",
# "countryName": "Romania",
# "cityName": "Cluj-Napoca"
# }